### PR TITLE
Bug fix

### LINKED ISSUE #105: Habit Events don't delete
Unfortunately when deleting a collection, Firebase doesn't propagate deletion to children collections, so our habit events aren't deleting.

### PR DESCRIPTION
**Pull request by JuliePilz**
Fixed bug associated with deleting habits.

closes #105

### CODE REVIEW

**Review by jaskim9824 — APPROVED** [review]

**Review by Nova-Drive — APPROVED** [review]

File: app/src/main/java/com/example/habitsmasher/ui/dashboard/HabitItemAdapter.java [hunk 1]
```diff
@@ -152,6 +163,11 @@ public void onClick(View v) {
                 public void onClick(View v) {
                     int habitPosition = getAdapterPosition();
                     Habit habitToDelete = _snapshots.get(habitPosition);
+                    try {
+                        deleteHabitEvents(username, habitToDelete);
+                    } catch(Error e) {
+                        Log.d(TAG, "No events to delete");
+                    }
```
Comment (rudy-patel) [inline app/src/main/java/com/example/habitsmasher/ui/dashboard/HabitItemAdapter.java:170]: Just a question here... So if an error occurs (meaning there were no events to delete), what happens? Are we still able to delete a habit with an empty event list? I think you mentioned that empty collections aren't possible, but I could be wrong.

**Review by rudy-patel — APPROVED** [review]
Just left a question there, but other than that this is great

**Review by kaden-dreger — APPROVED** [review]

File: app/src/main/java/com/example/habitsmasher/ui/dashboard/HabitItemAdapter.java (hunk 1 above)
Comment (JuliePilz) [reply app/src/main/java/com/example/habitsmasher/ui/dashboard/HabitItemAdapter.java:170]: Yep! If there's no habits in the list, there's actually nothing to delete. Collections are created whenever at least one item is attached, so if there's no habits in the list, there isn't actually a collection attached to the habit
