### PR TITLE
Privacy bug + Today fragment

### LINKED ISSUE #148: Update "Home" page to "Today"
The **home** page should be renamed to **today** since that is more consistent with the contents of the page. The icon can also be changed. You can get the "today" icon from: https://fonts.google.com/icons?selected=Material+Icons

image

### PR DESCRIPTION
**Pull request by Nova-Drive**
This PR fixes the privacy buttons bug, changes the home screen to the today screen (as well as renames home fragment to today fragment with the folder), and adds javadoc comments to the todayFragment.

This closes #148, #127, and #140.

image

### CODE REVIEW

File: app/src/androidTest/java/com/example/habitsmasher/MainActivityTest.java [hunk 1]
```diff
@@ -830,6 +831,132 @@ public void ensurePrivateHabitAdditionCorrect(){
...
+        // assert that the correct buttons are selected, not just the underlying habit
+        CheckBox publicBox = (CheckBox) _solo.getView(R.id.public_button);
+        CheckBox privateBox = (CheckBox) _solo.getView(R.id.private_button);
+        assertTrue(publicBox.isChecked());
+        assertFalse(privateBox.isChecked());
+
+        _solo.goBack();
+
+        deleteTestHabit(testHabit);
+    }
```
Comment (Nova-Drive) [inline app/src/androidTest/java/com/example/habitsmasher/MainActivityTest.java:958]: Two new tests for the invalid privacy choice error message.

File: app/src/main/java/com/example/habitsmasher/PublicPrivateButtons.java [hunk 2]
```diff
@@ -76,52 +66,51 @@ public PublicPrivateButtons(View view, boolean isPublic){
...
             public void onClick(View view) {
                 // if we check the public box, uncheck the private box
-                if (_privateSelected){
-                    _privateButton.performClick();
-                    _privateSelected = false;
+                if (_publicSelected){
+                    _publicSelected = false;
+                }
+                else {
                     _publicSelected = true;
```
Comment (Nova-Drive) [inline app/src/main/java/com/example/habitsmasher/PublicPrivateButtons.java:78]: Changed the logic to just track whether the buttons selected. Now both buttons or no buttons can be selected.

File: app/src/main/java/com/example/habitsmasher/PublicPrivateButtons.java [hunk 3]
```diff
@@ -76,52 +66,51 @@ public PublicPrivateButtons(View view, boolean isPublic){
...
 
+    /**
+     * Returns whether the private button is selected or not
+     * @return Status of the private button
+     */
+    public boolean isHabitPrivate(){
+        if (_privateSelected) return true;
+        else return false;
+    }
+
```
Comment (Nova-Drive) [inline app/src/main/java/com/example/habitsmasher/PublicPrivateButtons.java:114]: Figured if I had a method for public habits I should now have one for the private habits.

File: app/src/main/java/com/example/habitsmasher/ui/dashboard/HabitValidator.java [hunk 4]
```diff
@@ -38,12 +39,13 @@ public HabitValidator(DisplaysErrorMessages fragment) {
...
      * @param habitDate the habit date
      * @param tracker the tracker for days of the week
+     * @param privacyButtons
      * @return true, if habit is valid, false otherwise
      */
     public boolean isHabitValid(String habitTitle,
                                 String habitReason,
                                 String habitDate,
-                                DaysTracker tracker) {
+                                DaysTracker tracker, PublicPrivateButtons privacyButtons) {
```
Comment (Nova-Drive) [inline app/src/main/java/com/example/habitsmasher/ui/dashboard/HabitValidator.java:48]: Habit validator now takes the privacy buttons as a parameter.

File: app/src/main/java/com/example/habitsmasher/ui/dashboard/HabitValidator.java [hunk 5]
```diff
@@ -72,6 +74,15 @@ public boolean isHabitValid(String habitTitle,
...
         }
 
+        if (!(privacyButtons.isHabitPrivate() || privacyButtons.isHabitPublic())){
+            _fragment.displayErrorMessage(HabitDialog.INCORRECT_PRIVACY);
+            return false;
+        }
+        else if (privacyButtons.isHabitPrivate() && privacyButtons.isHabitPublic()){
+            _fragment.displayErrorMessage(HabitDialog.INCORRECT_PRIVACY);
+            return false;
+        }
```
Comment (Nova-Drive) [inline app/src/main/java/com/example/habitsmasher/ui/dashboard/HabitValidator.java:84]: Check whether no buttons are selected or both buttons are selected.

File: app/src/main/java/com/example/habitsmasher/ui/today/TodayFragment.java [hunk 6]
```diff
@@ -227,7 +226,11 @@ public void updateListAfterEdit(Object editedObject, int pos) {
         //not needed
     }
 
-    // helper method to make a habit
+    /**
+     * Helper method for making habits
+     * @param extractMap the information to make a habit
+     * @return new habit
+     */
```
Comment (Nova-Drive) [inline app/src/main/java/com/example/habitsmasher/ui/today/TodayFragment.java:233]: Turned all of the header comments into javadocs as per @rudy-patel's request.

File: app/src/main/res/drawable/ic_baseline_today_24.xml [hunk 7]
```diff
@@ -0,0 +1,10 @@
+<vector xmlns:android="http://schemas.android.com/apk/res/android"
+    android:width="24dp"
+    android:height="24dp"
+    android:viewportWidth="24"
+    android:viewportHeight="24"
+    android:tint="?attr/colorControlNormal">
+  <path
+      android:fillColor="@android:color/white"
+      android:pathData="M19,3h-1L18,1h-2v2L8,3L8,1L6,1v2L5,3c-1.11,0 -1.99,0.9 -1.99,2L3,19c0,1.1 0.89,2 2,2h14c1.1,0 2,-0.9 2,-2L21,5c0,-1.1 -0.9,-2 -2,-2zM19,19L5,19L5,8h14v11zM7,10h5v5L7,15z"/>
+</vector>
```
Comment (Nova-Drive) [inline app/src/main/res/drawable/ic_baseline_today_24.xml:10]: New icon for the todayFragment.

File: app/src/test/java/com/example/habitsmasher/ui/dashboard/HabitValidatorTest.java [hunk 8]
```diff
@@ -38,45 +37,45 @@ public void setUp() {
 
     @Test
     public void isHabitValid_allFieldsValid_expectHabitIsValid() {
-        assertTrue(_validator.isHabitValid(GOOD_TITLE, GOOD_REASON, TODAY, GOOD_TRACKER));
+        assertTrue(_validator.isHabitValid(GOOD_TITLE, GOOD_REASON, TODAY, GOOD_TRACKER, ));
```
Comment (Nova-Drive) [inline app/src/test/java/com/example/habitsmasher/ui/dashboard/HabitValidatorTest.java:40]: Didn't notice these, will fix right away.

File: app/src/main/java/com/example/habitsmasher/PublicPrivateButtons.java [hunk 9]
```diff
@@ -41,20 +45,34 @@ public PublicPrivateButtons(View view){
...
-
-        Log.d(TAG, String.valueOf(isPublic));
+        // get the buttons if they exist
+        try {
+            _publicButton = view.findViewById(R.id.public_button);
+            _privateButton = view.findViewById(R.id.private_button);
+        }
+        catch (Exception e){
+            Log.e(TAG, "PublicPrivateButtons: Buttons Not Found!", e);
+        }
```
Comment (Nova-Drive) [inline app/src/main/java/com/example/habitsmasher/PublicPrivateButtons.java:55]: These are for the testing, was having errors without these lines. Basically just ignores the buttons when running the habit validator unit tests.

File: app/src/main/java/com/example/habitsmasher/PublicPrivateButtons.java [hunk 10]
```diff
@@ -112,5 +130,16 @@ public boolean isHabitPrivate(){
...
+    /**
+     * Sets both buttons to whatever state given.
+     * @param publicButton the new public button state
+     * @param privateButton the new private button state
+     */
+    public void setButtons(boolean publicButton, boolean privateButton){
+        // This is actually a method I'm using for unit testing the validator
+        _publicSelected = publicButton;
+        _privateSelected = privateButton;
+    }
```
Comment (Nova-Drive) [inline app/src/main/java/com/example/habitsmasher/PublicPrivateButtons.java:142]: Helper method for the validator unit test, had to make it in class to access private fields.

File: app/src/test/java/com/example/habitsmasher/ui/dashboard/HabitValidatorTest.java [hunk 11]
```diff
@@ -37,45 +44,67 @@ public void setUp() {
...
+
+    @Test
+    public void isHabitValid_publicButtonSelected_expectHabitIsValid(){
+        assertTrue(_validator.isHabitValid(GOOD_TITLE, GOOD_REASON, TODAY, GOOD_TRACKER, GOOD_PRIVACY_BUTTONS));
+    }
+
+    @Test
+    public void isHabitValid_privateButtonSelected_expectHabitIsValid(){
+        GOOD_PRIVACY_BUTTONS.setButtons(false, true);
+        assertTrue(_validator.isHabitValid(GOOD_TITLE, GOOD_REASON, TODAY, GOOD_TRACKER, GOOD_PRIVACY_BUTTONS));
```
Comment (Nova-Drive) [inline app/src/test/java/com/example/habitsmasher/ui/dashboard/HabitValidatorTest.java]: Made more unit tests after fixing them. Can't believe I forgot to make the tests too...

File: app/src/main/java/com/example/habitsmasher/PublicPrivateButtons.java [hunk 12]
```diff
@@ -29,42 +29,50 @@
...
 
         // if its public, click the public button. if not, click the private button
         if (isPublic){
-            _publicButton.performClick();
-            _publicButton.setClickable(false);
+            // Catch error when buttons are not loaded
+            try {
+                _publicButton.performClick();
+            }
+            catch (Exception e){}
```
Comment (rudy-patel) [inline app/src/main/java/com/example/habitsmasher/PublicPrivateButtons.java:63]: Can we log the error message here as you did above?
- [ ] log error message

File: app/src/main/java/com/example/habitsmasher/PublicPrivateButtons.java [hunk 13]
```diff
@@ -29,42 +29,50 @@
...
         }
+
         else{
-            _privateButton.performClick();
-            _privateButton.setClickable(false);
+            // Catch error when buttons are not loaded
+            try {
+                _privateButton.performClick();
+            }
+            catch (Exception e){}
```
Comment (rudy-patel) [inline app/src/main/java/com/example/habitsmasher/PublicPrivateButtons.java:74]: Can we log the error message here as you did above?

- [ ] log error message

File: app/src/main/java/com/example/habitsmasher/PublicPrivateButtons.java [hunk 14]
```diff
@@ -76,52 +84,62 @@ public PublicPrivateButtons(View view, boolean isPublic){
...
         _publicButton.setOnClickListener(new View.OnClickListener() {
             @Override
             public void onClick(View view) {
                 // if we check the public box, uncheck the private box
-                if (_privateSelected){
-                    _privateButton.performClick();
-                    _privateSelected = false;
+                if (_publicSelected){
+                    _publicSelected = false;
+                }
```
Comment (rudy-patel) [inline app/src/main/java/com/example/habitsmasher/PublicPrivateButtons.java:94]: I'm having trouble following this conditional statement. Why do we need to set `_publicSelected` to false if it is true? I was imagining something like: if public is selected, private selected is false.

Could you explain this a bit?

File: app/src/main/java/com/example/habitsmasher/PublicPrivateButtons.java [hunk 15]
```diff
@@ -76,52 +84,62 @@ public PublicPrivateButtons(View view, boolean isPublic){
...
     /**
-     * Returns whether the public button is selected or not. Logically, if the public button is
-     * selected the private button is unselected, and vice versa.
-     * @return
+     * Returns whether the public button is selected or not.
+     * @return Status of the public button
      */
     public boolean isHabitPublic(){
         if (_publicSelected) return true;
         else return false;
```
Comment (rudy-patel) [inline app/src/main/java/com/example/habitsmasher/PublicPrivateButtons.java:121]: minor: this can be simplified to **just** this:
`
public boolean isHabitPublic() {
   return _publicSelected;
}
`

File: app/src/main/java/com/example/habitsmasher/PublicPrivateButtons.java [hunk 16]
```diff
@@ -76,52 +84,62 @@ public PublicPrivateButtons(View view, boolean isPublic){
...
     }
 
+    /**
+     * Returns whether the private button is selected or not
+     * @return Status of the private button
+     */
+    public boolean isHabitPrivate(){
+        if (_privateSelected) return true;
+        else return false;
+    }
```
Comment (rudy-patel) [inline app/src/main/java/com/example/habitsmasher/PublicPrivateButtons.java:131]: minor: this can be simplified to **just** this:
`
public boolean isHabitPrivate() {
   return _privateSelected;
}
`

File: app/src/main/java/com/example/habitsmasher/ui/dashboard/AddHabitDialog.java [hunk 17]
```diff
@@ -94,7 +94,7 @@ public void onClick(View view) {
                 // if the habit is valid, add it to the local list and external db
                 if (habitValidator.isHabitValid(habitTitle,
                                                 habitReason,
-                                                habitDate, _tracker)){
+                                                habitDate, _tracker, _publicPrivateButtons)){
```
Comment (rudy-patel) [inline app/src/main/java/com/example/habitsmasher/ui/dashboard/AddHabitDialog.java:97]: minor: can we new line the `tracker` and `publicPrivateButtons` so they follow the style of the other parameters?

File: app/src/main/java/com/example/habitsmasher/ui/dashboard/EditHabitDialog.java [hunk 18]
```diff
@@ -96,7 +96,7 @@ public void onClick(View v) {
                 // habit validator to ensure data is formatted appropriately
                 HabitValidator habitValidator = new HabitValidator(_editFragment);
 
-                if (!habitValidator.isHabitValid(habitTitle, reasonText, dateText, _tracker)) {
+                if (!habitValidator.isHabitValid(habitTitle, reasonText, dateText, _tracker, _publicPrivateButtons)) {
```
Comment (rudy-patel) [inline app/src/main/java/com/example/habitsmasher/ui/dashboard/EditHabitDialog.java:99]: minor: This line is getting long as well, so these parameters can also be on new lines for readability.

File: app/src/main/java/com/example/habitsmasher/ui/dashboard/HabitValidator.java (hunk 4 above)
Comment (rudy-patel) [reply app/src/main/java/com/example/habitsmasher/ui/dashboard/HabitValidator.java:48]: minor: should go on a new line to match the other parameters

File: app/src/main/java/com/example/habitsmasher/ui/dashboard/HabitValidator.java (hunk 5 above)
Comment (rudy-patel) [reply app/src/main/java/com/example/habitsmasher/ui/dashboard/HabitValidator.java:85]: Since both conditions lead to the **same outcome** (display the `INCORRECT_PRIVACY` error message), these should **either** be combined into one `if` block **or** display **different** error messages!

- [ ] fix `if` block

File: app/src/main/java/com/example/habitsmasher/ui/today/TodayFragment.java (hunk 6 above)
Comment (rudy-patel) [reply app/src/main/java/com/example/habitsmasher/ui/today/TodayFragment.java:233]: Love it, thanks man

File: app/src/main/java/com/example/habitsmasher/ui/today/TodayFragment.java [hunk 19]
```diff
@@ -237,26 +240,36 @@ private Habit makeHabit(Map<String, Object> extractMap) {
...
         return new Habit(title, reason, date.toDate(), days, isPublic, id, new HabitEventList());
     }
 
-    // get the current day of the week formatted as the first two letters of the day capitalized
-    // ex) "MO" or "TU"
+    /**
+     * get the current day of the week formatted as the first two letters of the day capitalized
+     * ex) "MO" or "TU"
+     * @return the current day
+     */
```
Comment (rudy-patel) [inline app/src/main/java/com/example/habitsmasher/ui/today/TodayFragment.java:251]: Thanks for remembering the `javadoc`!

**Review by rudy-patel — CHANGES_REQUESTED** [review]
Nice work Cam! Way to make the unit tests for the validator work with the front end stuff by mocking it out. 

Just left a few tasks on things that I think should be changed. I also left some comments, which are mostly minor styling issues but would be nice to fix in this PR as well. 

Once (at least) the **tasks** are taken care of, you have my approval!

File: app/src/main/java/com/example/habitsmasher/PublicPrivateButtons.java (hunk 14 above)
Comment (Nova-Drive) [reply app/src/main/java/com/example/habitsmasher/PublicPrivateButtons.java:94]: I've gone back and changed the logic for the buttons, now both can be pressed or not pressed at the same time. The new checks in the validator reflects the constraints of the button, where only one of the two may be checked.

File: .idea/misc.xml [hunk 20]
```diff
@@ -3,8 +3,11 @@
   <component name="DesignSurface">
     <option name="filePathToZoomLevelMap">
       <map>
+        <entry key="..\:/habitSmasher/app/src/main/res/layout/fragment_home.xml" value="0.2046875" />
```
Comment (rudy-patel) [inline .idea/misc.xml:6]: This looks like a local path judging by the `../:/habitSmasher`!

- [ ] remove local path

**Review by rudy-patel — CHANGES_REQUESTED** [review]
Way to get to all the feedback quickly! One last tiny thing is left... see the task that I left. After that, I'll happily approve.

**Review by rudy-patel — APPROVED** [review]

**Review by JacobNguyen71 — APPROVED** [review]
